iPMS/Controllers/ReportProblemController.cs
using iPMS.Helper;
using iPMS.Models;
using iPMS.Models.SessionModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace iPMS.Controllers
{
    public class ReportProblemController : BaseController
    {
        // GET: ReportProblem
        public ActionResult Index()
        {
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                return RedirectToAction("Index", "Login");
            }
            // เช็ค session expire

            ViewReportProblemModel model = new ViewReportProblemModel();

            model.SectionModelLists = Repository.StoredProcedure.SpReportProblem.SpGetReportProblemSection();

            ViewData["Department"] = profileData.DepartmentShort.Substring(0, 4);

            return View(model);
        }
        public ActionResult ProblemStatus()
        {
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                return RedirectToAction("Index", "Login");
            }
            // เช็ค session expire

            ViewReportProblemModel model = new ViewReportProblemModel();

            if(profileData.PermissionCode == "1")
            {
                model.ReportProblemModelLists = Repository.StoredProcedure.SpReportProblem.SpGetTableReportProblem(null,"1").ToList();
                model.ReportProblemStatusModelLists = Repository.StoredProcedure.SpReportProblem.SpGetReportProblemStatus().ToList();
            }
            else if(profileData.PermissionCode == "10") // โอนเรื่องไป กบล เนื่องจาก กบล เป็นแอดมิน (PermissionCode = 10)
            {
                model.ReportProblemModelLists = Repository.StoredProcedure.SpReportProblem.SpGetTableReportProblem(null,"2").ToList();
                model.ReportProblemStatusModelLists = Repository.StoredProcedure.SpReportProblem.SpGetReportProblemStatus("1").ToList();
            }
            else
            {
                model.ReportProblemModelLists = Repository.StoredProcedure.SpReportProblem.SpGetTableReportProblem(profileData.Username,"3");
                model.ReportProblemStatusModelLists = new List<ReportProblemStatusModel>();
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult Insert(ReportProblemModel model)
        {
            // สร้างตัวแปร
            String Message = "";
            String Status = "";
            // สร้างตัวแปร
            try
            {
                // เช็ค session expire
                var profileData = this.Session["UserProfile"] as UserProfileSessionData;
                if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
                {
                    MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                    var myData = new
                    {
                        Status = "-99", // Session หมด
                    };
                    return Json(myData);
                    //return Json("ไม่พบรหัสพนักงานคนดังกล่าว");
                }
                // เช็ค session expire

                try
                {
                    String ID = "";
                    (ID, Status, Message) = Repository.StoredProcedure.SpReportProblem.SpInsertReportProblem(model);
                    (Status, Message) = Repository.StoredProcedure.SpReportProblem.SpInsertReportProblemDetails(ID, model);
                    if(Status == "0")
                    {
                        var myData3 = new
                        {
                            Status = Status, // Update สำเร็จ
                            Message = Message,
                        };
                        return Json(myData3);
                    }
                    

                    string token = "Um8vecrhRQJ2tSmHddHr7QYloWOsT8stWyxu9aodLXi";
                    string msg = "";
                    msg = "ชื่อ : " + model.Name + "\n";
                    msg += "รหัสพนักงาน : " + model.EmployeeID + "\n";
                    msg += "สังกัด : " + model.BAName + "\n";
                    msg += "แผนก : " + model.Department + "\n";
                    msg += "เบอร์ติดต่อ : " + model.Tel + "\n";
                    msg += "เรื่อง : " + model.TitleText;
                    msg += "รายละเอียด : " + model.Details + "\n";
                    String Datetime = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
                    msg += "วันที่และเวลา : " + Datetime + "\n";

                    model.Title = Regex.Replace(model.Title, @"\s+", "");

                    int stickerPackageID = 6325;
                    int stickerID = 10979905;
                    var request = (HttpWebRequest)WebRequest.Create("https://notify-api.line.me/api/notify");
                    var postData = string.Format("message={0}", msg);
                    if (stickerPackageID > 0 && stickerID > 0)
                    {
                        var stickerPackageId = string.Format("stickerPackageId={0}", stickerPackageID);
                        var stickerId = string.Format("stickerId={0}", stickerID);
                        postData += "&" + stickerPackageId.ToString() + "&" + stickerId.ToString();
                    }
                    var data = Encoding.UTF8.GetBytes(postData);
                    request.Method = "POST";
                    request.ContentType = "application/x-www-form-urlencoded";
                    request.ContentLength = data.Length;
                    request.Headers.Add("Authorization", "Bearer " + token);

                    using (var stream = request.GetRequestStream())
                    {
                        stream.Write(data, 0, data.Length);
                    }

                    var response = (HttpWebResponse)request.GetResponse();
                    var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();

                    var myData2 = new
                    {
                        Status = Status, // Update สำเร็จ
                        Message = Message,
                    };
                    return Json(myData2);
                }
                catch (Exception ex)
                {
                    var myData3 = new
                    {
                        Status = "0", // Update สำเร็จ
                        Message = ex.ToString(),
                    };
                    return Json(myData3);
                }
            }
            catch (Exception ex) // กรณีมี Error ต่างๆ ให้ส่ง Error กลับไปที่ Ajax
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public ActionResult UpdateStatus(String ID,String Status,String IsTransfer, String Note)
        {
            // สร้างตัวแปร
            String Message = "";
            String StatusError = "";
            // สร้างตัวแปร
            try
            {
                // เช็ค session expire
                var profileData = this.Session["UserProfile"] as UserProfileSessionData;
                if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
                {
                    MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                    var myData = new
                    {
                        Status = "-99", // Session หมด
                    };
                    return Json(myData);
                    //return Json("ไม่พบรหัสพนักงานคนดังกล่าว");
                }
                // เช็ค session expire

                List<TableReportProblemModel> checks = Repository.StoredProcedure.SpReportProblem.SpGetTableReportProblem(null,"99",ID).ToList();
                if(checks[0].IsTransfer == "1")
                {
                    (StatusError, Message) = Repository.StoredProcedure.SpReportProblem.SpUpdateReportProblemDetails(ID, Status, "1", Note, profileData.Username);
                }
                else
                {
                    (StatusError, Message) = Repository.StoredProcedure.SpReportProblem.SpUpdateReportProblemDetails(ID, Status, IsTransfer, Note, profileData.Username);
                }

                var myData3 = new
                {
                    Status = StatusError, // Update สำเร็จ
                    Message = Message,
                    User = profileData.Username
                };
                return Json(myData3);
            }
            catch (Exception ex) // กรณีมี Error ต่างๆ ให้ส่ง Error กลับไปที่ Ajax
            {
                var myData = new
                {
                    Status = "0", // Update สำเร็จ
                    Message = ex.Message,
                };
                return Json(myData);
            }
        }
    }
}

iPMS/Views/ReportProblem/Index.cshtml
@using iPMS.Models.SessionModel
@model iPMS.Models.ViewReportProblemModel
@{
    var messageInfo = iPMS.Helper.MessageManager.GetMessage();
    var Employee = this.Session["UserProfile"] as UserProfileSessionData;
}
@functions{
    public long GenerateMath()
    {
        DateTime foo = DateTime.Now;
        long unixTime = ((DateTimeOffset)foo).ToUnixTimeSeconds();
        return unixTime;
    }
    public int StringToInt(String value)
    {
        return Int16.Parse(value);
    }
}
<link href="~/Repository/Template/spinner.css" rel="stylesheet">

<style>
    .btn-outline-danger:hover {
        background-color: white;
        color: #FF1616;
    }

    .btn-outline-success:hover {
        background-color: white;
        color: #7ED321;
    }

    .btn-outline-secondary {
        border-color: #6c757d;
        color: #6c757d;
    }

        .btn-outline-secondary:hover {
            background-color: white;
            color: #6c757d;
        }

    .btn-outline-warning:hover {
        background-color: white;
        color: #FFAA16;
    }
</style>
<div class="container-fluid">

    <div class="row page-titles mx-0">
        <div class="col-sm-12 p-md-0">
            <div class="welcome-text">
                <div class="text-center mb-4">
                    <h4>
                        แจ้งปัญหา
                    </h4>
                </div>
            </div>
        </div>
        <div class="card-body" style="margin-left:10px">
            <div class="basic-form">
                <form>

                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label>ชื่อ </label>
                            <label class="form-control" id="Name">@Employee.TitleFullName @Employee.FirstName @Employee.LastName</label>
                        </div>
                        <div class="form-group col-md-3">
                            <label>รหัสพนักงาน </label>
                            <label class="form-control" id="EmployeeID">@Employee.Username</label>
                        </div>
                        <div class="form-group col-md-3">
                            <label>สังกัด </label>
                            <label class="form-control" id="BAName">@Employee.BaName</label>
                        </div>
                        <div class="form-group col-md-3">
                            <label>แผนก </label>
                            <label class="form-control" id="Department">@ViewData["Department"]</label>
                        </div>
                        <div class="form-group col-md-3">
                            <label>เบอร์ติดต่อ </label><span class="text-danger"> *</span>
                            <input type="text" class="form-control" id="Tel" maxlength="50" placeholder="ตัวอย่าง 10365" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label>เรื่อง</label><span class="text-danger"> *</span>
                            <select id="Title" class="form-control">
                                <option value="" selected></option>
                                @foreach (var (item, index) in Model.SectionModelLists.Select((value, i) => (value, i)))
                                {
                                    <option value="@item.ID">@item.Title</option>
                                }
                                @*<option selected value="0">ปัญหาโปรแกรม</option>*@
                            </select>
                        </div>
                        
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label>รายละเอียด</label><span class="text-danger"> *</span>
                            <textarea class="form-control" id="Details" name="Details" rows="3" placeholder="" maxlength="500"></textarea>
                        </div>
                    </div>
                    <button type="button" class="btn btn-primary" onclick="Insert()">ยืนยัน</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    
    $(document).ready(function () {
        
    });

    function Insert() {
        let Name = $("#Name").text();
        @*let Result = $('input[name="Result"]:checked').val();*@
        let EmployeeID = $("#EmployeeID").text();
        let BAName = $("#BAName").text();
        let Department = $("#Department").text();
        let Tel = $("#Tel").val();
        let Title = $("#Title").val();
        let TitleText = $("#Title option:selected").text();
        let Details = $("#Details").val();
        
        
        if (!Tel) { // เช็ค
            let notifierCheckbox = document.getElementById("Tel");
            notifierCheckbox.focus();
            notifierCheckbox.setCustomValidity("โปรดกรอกเบอร์ติดต่อ เพื่อให้แอดมินสามารถติดต่อกลับได้.");
            notifierCheckbox.reportValidity();
            return;
        }
        if (!Title) { // เช็ค
            let notifierCheckbox = document.getElementById("Title");
            notifierCheckbox.focus();
            notifierCheckbox.setCustomValidity("โปรดเลือก เรื่องที่ต้องการจะแจ้ง.");
            notifierCheckbox.reportValidity();
            return;
        }
        if (!Details) { // เช็ค
            let notifierCheckbox = document.getElementById("Details");
            notifierCheckbox.focus();
            notifierCheckbox.setCustomValidity("โปรดระบุรายละเอียด.");
            notifierCheckbox.reportValidity();
            return;
        }

        var formData = new FormData();
        formData.append("Name", Name);
        formData.append("EmployeeID", EmployeeID);
        formData.append("BAName", BAName);
        formData.append("Department", Department);
        formData.append("Tel", Tel);
        formData.append("Title", Title); 
        formData.append("TitleText", TitleText);
        formData.append("Details", Details);

        $.ajax({
            url: "@Url.Action("Insert", "ReportProblem")",
            dataType: 'json',
            type: 'POST',
            data: formData,
            cache: false,
            processData: false,
            contentType: false,
            beforeSend: function () {
                // setting a timeout
                @*$("#BtnSave").attr("disabled", true);*@
            },
            success: function (data) {
                console.log(data);
                if (data["Status"] == "-99") {
                    location.reload();
                }
                else if (data["Status"] == "0") {
                    Swal.fire({
                        icon: 'error',
                        title: 'เกิดความผิดพลาด!',
                        text: data["Message"],
                    }).then(function () {
                        @*resetLabelAndBtn();*@
                    });
                }
                else if (data["Status"] == "1") {
                    Swal.fire(
                        'สำเร็จ',
                        data["Message"],
                        'success'
                    ).then(function () {
                        @*$('#exampleModalCenter').modal('hide');*@
                        location.reload();
                    });
                }
                else {
                    Swal.fire({
                        icon: 'error',
                        title: 'ไม่สามารถบันทึกได้',
                        text: data["Message"],
                    }).then(function () {

                    });
                }
            },
            error: function (d) {
                /*console.log("error");*/
                alert("404. Please wait until the File is Loaded.");
            }
        });
    }
</script>

iPMS/Views/ReportProblem/ProblemStatus.cshtml
@using iPMS.Models.SessionModel
@model iPMS.Models.ViewReportProblemModel
@{
    var messageInfo = iPMS.Helper.MessageManager.GetMessage();
    var Employee = this.Session["UserProfile"] as UserProfileSessionData;
}
@functions{
    public long GenerateMath()
    {
        DateTime foo = DateTime.Now;
        long unixTime = ((DateTimeOffset)foo).ToUnixTimeSeconds();
        return unixTime;
    }
    public int StringToInt(String value)
    {
        return Int16.Parse(value);
    }
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h1 class="">สถานะแจ้งปัญหา</h1>
                </div>
                <div class="card-body">
                    <div class="table-responsive">

                        <table class="table mb-0" id="list_table_json" name="list_table_json">
                            <thead style="color: #000000">
                                <tr>
                                    <th style="width: 150px">วันที่แจ้งปัญหา</th>
                                    <th style="width: 150px">ปัญหา</th>
                                    <th style="width: 300px">รายละเอียด</th>
                                    <th style="width: 200px">สถานะ</th>
                                    <th style="width: 100px">ผู้รับผิดชอบล่าสุด</th>
                                    <th style="width: 200px">หมายเหตุ</th>
                                    @if (@StringToInt(Employee.PermissionCode) >= 0 && @StringToInt(Employee.PermissionCode) <= 10)
                                    {
                                        <th style="width: 50px"></th>
                                    }

                                </tr>
                            </thead>
                            <tbody style="color: #000000">
                                @foreach (var (item, index) in Model.ReportProblemModelLists.Select((value, i) => (value, i)))
                                {
                                    <tr>
                                        <td>@item.DateTime.ToString("dd/MM/yyyy HH:mm")</td>
                                        <td>@item.TitleDesc</td>
                                        <td>@item.Details</td>
                                        <td>@item.Describetion</td>
                                        <td>@item.Responsible</td>
                                        <td>@item.Note</td>
                                        @if (@StringToInt(Employee.PermissionCode) >= 0 && @StringToInt(Employee.PermissionCode) <= 10)
                                        {
                                            <td>
                                                @if(item.Complete != "1")
                                                {
                                                    <button type="button" id="@item.ID" class="btn btn-primary-outline"
                                                        onclick="OpenModal(this.id,@index)" data-id=""
                                                        title="ตรวจสอบ">
                                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                                                        </svg>
                                                    </button>
                                                }
                                            </td>
                                        }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade bd-example-modal-xl" id="exampleModalCenter" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">อัปเดตสถานะ</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="card-body">
                    <div class="basic-form">
                        <form>
                            <input type="hidden" id="HiddenID" />
                            <input type="hidden" id="HiddensetRow" />

                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label" style="color:black">สถานะ<span class="text-danger"> * </span></label>
                                <div class="col-sm-8">
                                    <select class="form-control" id="Status" name="Status">
                                        <option value="" selected>Please select</option>
                                        @foreach (var (item, index) in Model.ReportProblemStatusModelLists.Select((value, i) => (value, i)))
                                        {
                                            <option value="@item.ID" data-year="@item.IsTransfer" data-third="@item.Complete" >@item.Describetion</option>
                                        }
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row" id="HiddenNote">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="Note" class="col-form-label" style="color:black">หมายเหตุ </label>
                                        <textarea class="form-control" id="Note" maxlength="200" style="color:black"></textarea>
                                    </div>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">ปิด</button>
                <button type="button" class="btn btn-primary" onclick="Insert()">บันทึก</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#list_table_json').DataTable({
            //"scrollX": true,
            //"scrollY": true,
            "language": {

                "search": '<i class="fa fa-search"></i>',
                "searchPlaceholder": "search",
            }, "aaSorting": []
        });
        if (@Employee.IsLogin != "1") {
            location.reload();
        }

    });
    function OpenModal(ID, index) {
        $('#HiddenID').val(ID);
        $('#HiddensetRow').val(index);
        $('#Status').val('');
        $('#exampleModalCenter').modal('show');
    }
    function Insert() {
        let Status = $("#Status").val();
        let IsTransfer = $('#Status').find(':selected').data("year");
        let Complete = $('#Status').find(':selected').data("third");
        let Note = $("#Note").val();
        let ID = $('#HiddenID').val();
        let rowIndex = $('#HiddensetRow').val();

        if (!Status) { // เช็ค
            let notifierCheckbox = document.getElementById("Status");
            notifierCheckbox.focus();
            notifierCheckbox.setCustomValidity("โปรดเลือกสถานะที่ต้องการอัปเดต.");
            notifierCheckbox.reportValidity();
            return;
        }

        $.ajax({
            type: "POST",
            url: '@Url.Action("UpdateStatus", "ReportProblem")',
            data: { ID: ID, Status: Status, IsTransfer: IsTransfer, Note: Note },
            dataType: "json",
            success: function (data) {
                @*console.log(data);*@

                if(data["Status"] == "-99") {
                    location.reload();
                }
                else if (data["Status"] == "1") {
                    @*$('#Report').val(data["Data"][0].Report);
                    $('#PerformanceText').val(data["Data"][0].PerformanceText);
                    $('#PerformanceText2').val(data["Data"][0].PerformanceText2);*@

                    Swal.fire(
                        'สำเร็จ',
                        data["Message"],
                        'success'
                    ).then(function () {

                        // ดึง Datatable มาอัปเดต หน้าต่างข้อมูล
                        var table = $('#list_table_json').DataTable();
                        var idx = table
                            .row(rowIndex)
                            .index();
                        @* table.cell(idx, 1).data(BA).draw();
                        table.cell(idx, 2).data(Agency).draw();*@

                        table.cell(idx, 3).data($("#Status option:selected").text()).draw();
                        table.cell(idx, 4).data(data["User"]).draw();
                        if (Complete == "1") {
                            table.cell(idx, 5).data('').draw();
                        }
                        @* table.cell(idx, 4).data(IPAddress).draw();*@
                        @* location.reload();*@

                        $("#Status").val('');
                        $("#Note").val('');

                        $('#exampleModalCenter').modal('hide');
                    });
                }
                else {
                    Swal.fire({
                        icon: 'error',
                        title: 'เกิดความผิดพลาด!',
                        text: data["Message"],
                    }).then(function () {

                    });
                }
            },
            error: function (error) {
                Swal.fire({
                    icon: 'error',
                    title: 'เกิดความผิดพลาด!',
                    text: error["Message"],
                })
            }
        });
    }
</script>