iPMS/Controllers/DeveloperController.cs
using iPMS.Helper;
using iPMS.Models.SessionModel;
using iPMS.ServiceReference2;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iPMS.Controllers
{
    public class DeveloperController : BaseController
    {
        private Guid guidOutput;

        // GET: Delveoper
        public ActionResult Index()
        {
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                return RedirectToAction("Index", "Login");
            }
            // เช็ค session expire
            return View();
        }

        [HttpPost]
        public ActionResult DeleteSection(String Key,String Key2,String EmployeeID)
        {
            string controllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
            string actionName = this.ControllerContext.RouteData.Values["action"].ToString();
            String Status = "", Message = "";
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                var myData = new
                {
                    Status = "-99", // Session หมด
                };
                return Json(myData);
            }
            else if (profileData.PermissionCode != "1") // เช็คสิทธิ์ผู้พัฒนาระบบ
            {
                MessageManager.SetErrorMessage("คุณไม่มีสิทธิ์ในการใช้ฟังก์ชันนี้ กรุณาล็อคอินใหม่อีกครั้ง");
                var myData = new
                {
                    Status = "-99", // เตะให้ไปล็อคอินใหม่
                };
                return Json(myData);
            }
            //EmployeeProfile employeeProfile = IdmManager.GetByEmployeeNo(EmployeeID);

            UserProfileSessionData ResponseprofileData = new UserProfileSessionData();
            (ResponseprofileData, Status, Message) = getHrPlatform(EmployeeID);

            if (ResponseprofileData == null)
            {
                var myData = new
                {
                    Status = "0", // เตะให้ไปล็อคอินใหม่
                    Message = "ไม่มีรหัสพนักงานดังกล่าว"
                };
                return Json(myData);
            }
            // เช็ค session expire
            bool isValidKey1 = Guid.TryParse(Key, out guidOutput);
            bool isValidKey2 = Guid.TryParse(Key2, out guidOutput);
            if (!isValidKey1 || !isValidKey2)
            {
                var myData3 = new
                {
                    Status = 0,
                    Message = "กรุณาตรวจสอบคีย์ถูกต้องหรือไม่",
                };
                return Json(myData3);
            }
            int row;

            Message = EmployeeID + " " + "ได้แจ้งเข้ามาให้ทำการลบ";
            (Status, Message,row) = Repository.StoredProcedure.SpDeveloper.SpDeleteSection(Key, Key2, profileData.Username, controllerName, actionName, "Success", Message);
            if(row <= 1 && Status == "1")
            {
                var myData3 = new
                {
                    Status = 0,
                    Message = "กรุณาตรวจสอบคีย์ถูกต้องหรือไม่",
                    row = row,
                };
                return Json(myData3);
            }
            var myData2 = new
            {
                Status = Status,
                Message = Message,
                row = row,
            };
            return Json(myData2);
        }
    }
}

iPMS/Views/Developer/Index.cshtml
@using iPMS.Models.SessionModel
@model iPMS.Models.ViewActionPlanModel

@{
    var messageInfo = iPMS.Helper.MessageManager.GetMessage();
    var Employee = this.Session["UserProfile"] as UserProfileSessionData;
}

@functions{
    public long GenerateMath()
    {
        DateTime foo = DateTime.Now;
        long unixTime = ((DateTimeOffset)foo).ToUnixTimeSeconds();
        return unixTime;
    }
}



<style>
    @*.content-body {
        background: #e4e4e5;
        padding-bottom: 40px;
    }*@

    @*.card-body {
        background: #fff;
        border-radius: 8px;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        align-self: flex-start;
        padding: 25px;
        width: 70%;
        min-width: 900px;
        box-shadow: 0 0 0 1px rgb(53 72 91 / 7%), 0 2px 2px rgb(0 0 0 / 1%), 0 4px 4px rgb(0 0 0 / 2%), 0 10px 8px rgb(0 0 0 / 3%), 0 15px 15px rgb(0 0 0 / 3%), 0 30px 30px rgb(0 0 0 / 4%), 0 70px 65px rgb(0 0 0 / 5%)
    }*@

    .table_row {
        border-bottom: 1px solid #d7d4e4;
        background: #fff;
        padding: 10px
    }

    .yeartext_column {
        width: fit-content;
        text-align: center;
        vertical-align: middle;
        font-size: 24px;
        font-weight: bold;
        color: #7f4197;
        padding: 10px;
    }

    .filenametext_column {
        font-size: 24px;
        color: #9a9a9a;
        text-align: start;
        padding: 10px;
        padding-right: 20px;
    }

    .download_button_column {
        cursor: pointer;
        background: #fff;
    }

    .download_button_column > a {
        border: 1px solid #d7d4e4;
        border-radius: 8px;
        padding: 10px;
        background: #fff;
    }
    table td input {
        display: block;
        top: 0;
        left: 0;
        margin: 0;
        height: 100%;
        width: 100%;
        border: none;
        padding: 10px;
    }
    .form-control{
        display: block;
        top: 0;
        left: 0;
        margin: 0;
        height: 100%;
        width: 100%;
        border: none;
        padding: 10px;
        font-size:18px;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="text">
                        <p style="font-size: 32px; color: #444444; margin-bottom: 40px; text-align: center;">
                            จัดการผลดำเนินงานที่มีผลการลงคะแนนแล้ว
                        </p>
                    </div>

                    @*<div class="text">
                        <p style="font-size: 24px; color: #444444; padding-left: 15px">ดาวน์โหลดเอกสาร</p>
                    </div>*@


                    <div style="width: 100%; height: 600px; padding-left: 15px">
                        <table class="file_table" >
                            <thead>
                                <tr class="table_row">
                                    <td class="yeartext_column" >
                                        คีย์หลัก
                                    </td>
                                    <td class="filenametext_column" id="TextFiles" >
                                        <input class="form-control" type="text" placeholder="36E1C1E9-743D-478B-A319-77565AF67CC8" id="Key">
                                    </td>
                                    <td class="download_button_column">
                                    </td>
                                </tr>
                                <tr class="table_row">
                                    <td class="yeartext_column">
                                        คีย์สำรอง
                                    </td>
                                    <td class="filenametext_column" id="TextFiles" >
                                        <input class="form-control" type="text" placeholder="36E1C1E9-743D-478B-A319-77565AF67CC8" id="Key2">
                                    </td>
                                    <td class="download_button_column">
                                    </td>
                                </tr>
                                <tr class="table_row">
                                    <td class="yeartext_column">
                                        ผู้แจ้ง
                                    </td>
                                    <td class="filenametext_column" id="TextFiles">
                                        <input class="form-control" type="text" placeholder="รหัสพนักงาน" id="EmployeeID">
                                    </td>
                                    <td class="download_button_column">
                                    </td>
                                </tr>
                                <tr class="">
                                    <td class="yeartext_column">
                                        &nbsp;
                                    </td>
                                    <td class="filenametext_column" id="TextFiles">
                                    </td>
                                    <td class="download_button_column">
                                        <a class="btn" onclick="Delete()"
                                           title="ยืนยัน" id="btnConfirm">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-check" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M5 12l5 5l10 -10" />
                                            </svg>
                                        </a>
                                    </td>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    function Delete() {
        let Key = $('#Key').val();
        let Key2 = $('#Key2').val();
        let EmployeeID = $('#EmployeeID').val();
        if (Key == "") { // เช็ค
            let notifierCheckbox = document.getElementById("Key");
            notifierCheckbox.focus();
            notifierCheckbox.setCustomValidity("โปรดระบุคีย์หลัก.");
            notifierCheckbox.reportValidity();
            return;
        }
        if (Key2 == "") { // เช็ค
            let notifierCheckbox = document.getElementById("Key2");
            notifierCheckbox.focus();
            notifierCheckbox.setCustomValidity("โปรดระบุคีย์สำรอง.");
            notifierCheckbox.reportValidity();
            return;
        }
        if (EmployeeID == "") { // เช็ค
            let notifierCheckbox = document.getElementById("EmployeeID");
            notifierCheckbox.focus();
            notifierCheckbox.setCustomValidity("โปรดระบุรหัสพนักงาน.");
            notifierCheckbox.reportValidity();
            return;
        }

        $.ajax({
            type: "POST",
            url: '@Url.Action("DeleteSection", "Developer")',
            data: { Key: Key, Key2: Key2, EmployeeID: EmployeeID},
            dataType: "json",
            beforeSend: function () {
                // setting a timeout
            },
            success: function (data) {
                console.log(data)
                if (data["Status"] == "-99") {
                    location.reload();
                }
                else if (data["Status"] == "1") {
                    console.log(data);
                    var str = data["Message"] + "\n" +
                        "จำนวน " + (data["row"]-1) +" แถว\n";
                     Swal.fire(
                        'สำเร็จ',
                         '<pre>' + str + '</pre>',
                        'success'
                     ).then(function () {
                         @*$("#loadMe").modal("hide");*@
                         $('#Key').val('');
                         $('#Key2').val('');
                         $('#EmployeeID').val('');

                     });
                }
                else {
                     Swal.fire({
                        icon: 'error',
                        title: 'เกิดความผิดพลาด!',
                        text: data["Message"],
                     }).then(function () {
                         $('#Key').val('');
                         $('#Key2').val('');
                         $('#EmployeeID').val('');
                     });
                }
            },
            error: function (error) {
                @*alert(error);*@
                @*$("#loadMe").modal("hide");*@

                Swal.fire({
                    icon: 'error',
                    title: 'เกิดความผิดพลาด!',
                    text: error["Message"],
                })
            }
        });
    }
</script>