iPMS/Controllers/ActionPlanController.cs
using iPMS.Helper;
using iPMS.Models;
using iPMS.Models.SessionModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace iPMS.Controllers
{
    public class ActionPlanController : BaseController
    {
        // GET: ActionPlan
        public ActionResult Index()
        {
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                return RedirectToAction("Index", "Login");
            }
            // เช็ค session expire
            return View();
        }
        //public ActionResult SocietyAndEnvironment()
        //{
        //    // เช็ค session expire
        //    var profileData = this.Session["UserProfile"] as UserProfileSessionData;
        //    if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
        //    {
        //        MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
        //        return RedirectToAction("Index", "Login");
        //    }
        //    // เช็ค session expire

        //    String ID = null;
        //    String TypeID = "3"; // แผนปฏิบัติ
        //    String CabinetID = "1"; // นิยามแผนปฏิบัติการ
        //    String TopicID = "1"; // ด้านสังคม
        //    String Year = null; // ปี
        //    String PEAID = null;
        //    String TimesAYearID = null;
        //    String Quarter = null; 
        //    String Status = "";
        //    String Message = "";
        //    ViewActionPlanModel viewModel = new ViewActionPlanModel();

        //    viewModel.YearsModelLists = Repository.StoredProcedure.SpPerformanceAnalysis.SpGetTimesAYear(CabinetID,TopicID).ToList();
        //    Year = viewModel.YearsModelLists[0].Year;
        //    (viewModel.ArchiveModelLists, Status, Message) = Repository.StoredProcedure.SpActionPlan
        //        .SpGetArchive(ID, TypeID, CabinetID, TopicID, Year, PEAID, TimesAYearID, Quarter);

        //    ViewData["Year"] = viewModel.YearsModelLists[0].Year;
        //    ViewData["TopicName"] = "ด้านสังคมและสิ่งแวดล้อม";

        //    return View(viewModel);
        //}
        //public ActionResult Finance()
        //{
        //    // เช็ค session expire
        //    var profileData = this.Session["UserProfile"] as UserProfileSessionData;
        //    if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
        //    {
        //        MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
        //        return RedirectToAction("Index", "Login");
        //    }
        //    // เช็ค session expire

        //    String ID = null;
        //    String TypeID = "3"; // แผนปฏิบัติ
        //    String CabinetID = "1"; // นิยามแผนปฏิบัติการ
        //    String TopicID = "2"; // ด้านการเงิน
        //    String Year = null; // ปี
        //    String PEAID = null;
        //    String TimesAYearID = null;
        //    String Quarter = null;
        //    String Status = "";
        //    String Message = "";
        //    ViewActionPlanModel viewModel = new ViewActionPlanModel();

        //    viewModel.YearsModelLists = Repository.StoredProcedure.SpPerformanceAnalysis.SpGetTimesAYear(CabinetID).ToList();
        //    Year = viewModel.YearsModelLists[0].Year;
        //    (viewModel.ArchiveModelLists, Status, Message) = Repository.StoredProcedure.SpActionPlan
        //        .SpGetArchive(ID, TypeID, CabinetID, TopicID, Year, PEAID, TimesAYearID, Quarter);

        //    ViewData["Year"] = viewModel.YearsModelLists[0].Year;
        //    ViewData["TopicName"] = "ด้านการเงิน";

        //    return View(viewModel);
        //}
        public ActionResult Target()
        {
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                return RedirectToAction("Index", "Login");
            }
            // เช็ค session expire

            String ID = null;
            String TypeID = "3"; // แผนปฏิบัติ
            String CabinetID = "1"; // นิยามแผนปฏิบัติการ
            String TopicID = "1"; // ด้านเป้าหมาย
            String Year = null; // ปี
            String PEAID = null;
            String TimesAYearID = null;
            String Quarter = null;
            String Status = "";
            String Message = "";
            ViewActionPlanModel viewModel = new ViewActionPlanModel();

            viewModel.YearsModelLists = Repository.StoredProcedure.SpPerformanceAnalysis.SpGetTimesAYear(CabinetID,TopicID).ToList();

            (viewModel.ArchiveModelLists, Status, Message) = Repository.StoredProcedure.SpActionPlan
                .SpGetArchive(ID, TypeID, CabinetID, TopicID, Year, PEAID, TimesAYearID, Quarter);

            if(viewModel.YearsModelLists.Count == 0)
            {
                Year = DateTime.Now.Year.ToString(); // ปีปัจจุบัน;
                ViewData["Year"] = DateTime.Now.Year.ToString(); // ปีปัจจุบัน;
            }
            else
            {
                Year = viewModel.YearsModelLists[0].Year;
                ViewData["Year"] = viewModel.YearsModelLists[0].Year;
            }
            ViewData["TopicName"] = "ด้านเป้าหมาย";
            ViewData["TopicID"] = TopicID;

            return View(viewModel);
        }
        public ActionResult Customer()
        {
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                return RedirectToAction("Index", "Login");
            }
            // เช็ค session expire

            String ID = null;
            String TypeID = "3"; // แผนปฏิบัติ
            String CabinetID = "1"; // นิยามแผนปฏิบัติการ
            String TopicID = "2"; // ด้านลูกค้า
            String Year = null; // ปี
            String PEAID = null;
            String TimesAYearID = null;
            String Quarter = null;
            String Status = "";
            String Message = "";
            ViewActionPlanModel viewModel = new ViewActionPlanModel();

            viewModel.YearsModelLists = Repository.StoredProcedure.SpPerformanceAnalysis.SpGetTimesAYear(CabinetID, TopicID).ToList();

            (viewModel.ArchiveModelLists, Status, Message) = Repository.StoredProcedure.SpActionPlan
                .SpGetArchive(ID, TypeID, CabinetID, TopicID, Year, PEAID, TimesAYearID, Quarter);

            if (viewModel.YearsModelLists.Count == 0)
            {
                Year = DateTime.Now.Year.ToString(); // ปีปัจจุบัน;
                ViewData["Year"] = DateTime.Now.Year.ToString(); // ปีปัจจุบัน;
            }
            else
            {
                Year = viewModel.YearsModelLists[0].Year;
                ViewData["Year"] = viewModel.YearsModelLists[0].Year;
            }
            ViewData["TopicName"] = "ด้านลูกค้า";
            ViewData["TopicID"] = TopicID;

            return View(viewModel);
        }
        public ActionResult Internal()
        {
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                return RedirectToAction("Index", "Login");
            }
            // เช็ค session expire

            String ID = null;
            String TypeID = "3"; // แผนปฏิบัติ
            String CabinetID = "1"; // นิยามแผนปฏิบัติการ
            String TopicID = "3"; // ด้านกระบวนการภายใน
            String Year = null; // ปี
            String PEAID = null;
            String TimesAYearID = null;
            String Quarter = null;
            String Status = "";
            String Message = "";
            ViewActionPlanModel viewModel = new ViewActionPlanModel();

            viewModel.YearsModelLists = Repository.StoredProcedure.SpPerformanceAnalysis.SpGetTimesAYear(CabinetID, TopicID).ToList();

            (viewModel.ArchiveModelLists, Status, Message) = Repository.StoredProcedure.SpActionPlan
                .SpGetArchive(ID, TypeID, CabinetID, TopicID, Year, PEAID, TimesAYearID, Quarter);

            if (viewModel.YearsModelLists.Count == 0)
            {
                Year = DateTime.Now.Year.ToString(); // ปีปัจจุบัน;
                ViewData["Year"] = DateTime.Now.Year.ToString(); // ปีปัจจุบัน;
            }
            else
            {
                Year = viewModel.YearsModelLists[0].Year;
                ViewData["Year"] = viewModel.YearsModelLists[0].Year;
            }
            ViewData["TopicName"] = "ด้านกระบวนการภายใน";
            ViewData["TopicID"] = TopicID;

            return View(viewModel);
        }
        public ActionResult LearningAndDevelopment()
        {
            // เช็ค session expire
            var profileData = this.Session["UserProfile"] as UserProfileSessionData;
            if (CheckSession(profileData) == 0)//// ยังไม่ได้ล็อคอิน
            {
                MessageManager.SetErrorMessage("โปรดล็อคอินเพื่อเข้าสู่ระบบใหม่อีกครั้ง");
                return RedirectToAction("Index", "Login");
            }
            // เช็ค session expire

            String ID = null;
            String TypeID = "3"; // แผนปฏิบัติ
            String CabinetID = "1"; // นิยามแผนปฏิบัติการ
            String TopicID = "4"; // ด้านเรียนรู้และพัฒนา
            String Year = null; // ปี
            String PEAID = null;

iPMS/Views/ActionPlan/Customer.cshtml
@using iPMS.Models.SessionModel
@model iPMS.Models.ViewActionPlanModel

@{
    var messageInfo = iPMS.Helper.MessageManager.GetMessage();
    var Employee = this.Session["UserProfile"] as UserProfileSessionData;
}

@functions{
    public long GenerateMath()
    {
        DateTime foo = DateTime.Now;
        long unixTime = ((DateTimeOffset)foo).ToUnixTimeSeconds();
        return unixTime;
    }
}



<style>
    @*.content-body {
        background: #e4e4e5;
        padding-bottom: 40px;
    }*@

    @*.card-body {
        background: #fff;
        border-radius: 8px;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        align-self: flex-start;
        padding: 25px;
        width: 70%;
        min-width: 900px;
        box-shadow: 0 0 0 1px rgb(53 72 91 / 7%), 0 2px 2px rgb(0 0 0 / 1%), 0 4px 4px rgb(0 0 0 / 2%), 0 10px 8px rgb(0 0 0 / 3%), 0 15px 15px rgb(0 0 0 / 3%), 0 30px 30px rgb(0 0 0 / 4%), 0 70px 65px rgb(0 0 0 / 5%)
    }*@

    .table_row {
        border-bottom: 1px solid #d7d4e4;
        background: #fff;
        padding: 10px
    }

    .yeartext_column {
        width: fit-content;
        text-align: center;
        vertical-align: middle;
        font-size: 24px;
        font-weight: bold;
        color: #7f4197;
        padding: 10px;
    }

    .filenametext_column {
        font-size: 24px;
        color: #9a9a9a;
        text-align: start;
        padding: 10px;
        padding-right: 80px;
    }

    .download_button_column {
        cursor: pointer;
        background: #fff;
    }

        .download_button_column > a {
            border: 1px solid #d7d4e4;
            border-radius: 8px;
            padding: 10px;
            background: #fff;
        }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="text">
                        <p style="font-size: 32px; color: #444444; margin-bottom: 40px; text-align: center;">
                            นิยามแผนปฏิบัติการ "@ViewData["TopicName"]"
                            <span id="SpanYear"> @ViewData["Year"] </span>
                        </p>
                    </div>

                    <div class="col-sm-3">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text mb-4">เลือกปี</span>
                            </div>
                            <select id="Year" name="Filter" class="form-control">
                                @foreach (var (item, index) in Model.YearsModelLists.Select((value, i) => (value, i)))
                                {
                                    if (ViewData["Year"] as string == item.Year)
                                    {
                                        <option value="@item.Year" selected>@item.Year</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Year">@item.Year</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>

                    <div class="text">
                        <p style="font-size: 24px; color: #444444; padding-left: 15px">ดาวน์โหลดเอกสาร</p>
                    </div>

                    @foreach (var (item, index) in Model.ArchiveModelLists.Select((value, i) => (value, i)))
                    {
                        <div style="width: 100%; height: 600px; padding-left: 15px">
                            <table class="file_table">
                                <thead>
                                    <tr class="table_row">
                                        <td class="yeartext_column">
                                            ประจำปี <span id="SpanYear2"> @item.Year </span> :
                                        </td>
                                        <td class="filenametext_column" id="TextFiles">
                                            @item.FileName
                                        </td>
                                        <td class="download_button_column">

                                            <a class="btn" href="~/Repository/PDF/ActionPlan/@item.FileName?@GenerateMath()"
                                               target="_blank" title="ไฟล์เอกสาร" id="LinkFiles">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-book-download" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="#444" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                                    <path d="M12 20h-6a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12v5"></path>
                                                    <path d="M13 16h-7a2 2 0 0 0 -2 2"></path>
                                                    <path d="M15 19l3 3l3 -3"></path>
                                                    <path d="M18 22v-9"></path>
                                                </svg>
                                            </a>
                                        </td>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    const quarter = ["ไตรมาส 1", "ไตรมาส 1-2", "ไตรมาส 1-3", "ไตรมาส 1-4"];
    function getquarter(month) {
        return quarter[month - 1];
    }

    $('select[name="Filter"]').change(function (e) {
        let Year = $('#Year').val();
        let TopicID = '@ViewData["TopicID"]';
        $.ajax({
            type: "POST",
            url: '@Url.Action("FilterYear", "ActionPlan")',
            data: { Year: Year, TopicID: TopicID},
            dataType: "json",
            beforeSend: function () {
                // setting a timeout
                @*$("#loadMe").modal({
                    backdrop: "static", //remove ability to close modal with click
                    keyboard: false, //remove option to close with keyboard
                    show: true //Display loader!
                });*@
            },
            success: function (data) {
                console.log(data)
                if (data["Status"] == "-99") {
                    location.reload();
                }
                else if (data["Status"] == "1") {
                     @*console.log(data);*@

                     @*$("#loadMe").modal("hide");*@
                     Swal.fire(
                        'สำเร็จ',
                        data["Message"],
                        'success'
                     ).then(function () {
                         @*$("#loadMe").modal("hide");*@
                         $('#SpanYear').text(data["Data"][0].Year);
                         $('#SpanYear2').text(data["Data"][0].Year);
                         $('#TextFiles').text(data["Data"][0].FileName);
                         $("#LinkFiles").attr("href", "../Repository/PDF/ActionPlan/" + data["Data"][0].FileName + "?@GenerateMath()");

                     });
                }
                else {
                     Swal.fire({
                        icon: 'error',
                        title: 'เกิดความผิดพลาด!',
                        text: data["Message"],
                     }).then(function () {
                         @*$("#loadMe").modal("hide");*@
                         $('#SpanYear').text(Year);
                         $('#SpanYear2').text(Year);
                         $('#TextFiles').text("");
                         $("#LinkFiles").attr("href", "javascript:toggleMe(0);");
                     });
                }
            },
            error: function (error) {
                @*alert(error);*@
                @*$("#loadMe").modal("hide");*@

                Swal.fire({
                    icon: 'error',
                    title: 'เกิดความผิดพลาด!',
                    text: error["Message"],
                })
            }
        });
    });
</script>

iPMS/Views/ActionPlan/Finance.cshtml
@using iPMS.Models.SessionModel
@model iPMS.Models.ViewActionPlanModel

@{
    var messageInfo = iPMS.Helper.MessageManager.GetMessage();
    var Employee = this.Session["UserProfile"] as UserProfileSessionData;
}

@functions{
    public long GenerateMath()
    {
        DateTime foo = DateTime.Now;
        long unixTime = ((DateTimeOffset)foo).ToUnixTimeSeconds();
        return unixTime;
    }
}



<style>
    @*.content-body {
        background: #e4e4e5;
        padding-bottom: 40px;
    }*@

    @*.card-body {
        background: #fff;
        border-radius: 8px;
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        align-self: flex-start;
        padding: 25px;
        width: 70%;
        min-width: 900px;
        box-shadow: 0 0 0 1px rgb(53 72 91 / 7%), 0 2px 2px rgb(0 0 0 / 1%), 0 4px 4px rgb(0 0 0 / 2%), 0 10px 8px rgb(0 0 0 / 3%), 0 15px 15px rgb(0 0 0 / 3%), 0 30px 30px rgb(0 0 0 / 4%), 0 70px 65px rgb(0 0 0 / 5%)
    }*@

    .table_row {
        border-bottom: 1px solid #d7d4e4;
        background: #fff;
        padding: 10px
    }

    .yeartext_column {
        width: fit-content;
        text-align: center;
        vertical-align: middle;
        font-size: 24px;
        font-weight: bold;
        color: #7f4197;
        padding: 10px;
    }

    .filenametext_column {
        font-size: 24px;
        color: #9a9a9a;
        text-align: start;
        padding: 10px;
        padding-right: 80px;
    }

    .download_button_column {
        cursor: pointer;
        background: #fff;
    }

        .download_button_column > a {
            border: 1px solid #d7d4e4;
            border-radius: 8px;
            padding: 10px;
            background: #fff;
        }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="text">
                        <p style="font-size: 32px; color: #444444; margin-bottom: 40px; text-align: center;">
                            นิยามแผนปฏิบัติการ "@ViewData["TopicName"]"
                            <span id="SpanYear"> @ViewData["Year"] </span>
                        </p>
                    </div>

                    <div class="col-sm-3">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text mb-4">เลือกปี</span>
                            </div>
                            <select id="Year" name="Filter" class="form-control">
                                @foreach (var (item, index) in Model.YearsModelLists.Select((value, i) => (value, i)))
                                {
                                    if (ViewData["Year"] as string == item.Year)
                                    {
                                        <option value="@item.Year" selected>@item.Year</option>
                                    }
                                    else
                                    {
                                        <option value="@item.Year">@item.Year</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>

                    <div class="text">
                        <p style="font-size: 24px; color: #444444; padding-left: 15px">ดาวน์โหลดเอกสาร</p>
                    </div>

                    @foreach (var (item, index) in Model.ArchiveModelLists.Select((value, i) => (value, i)))
                    {
                        <div style="width: 100%; height: 600px; padding-left: 15px">
                            <table class="file_table">
                                <thead>
                                    <tr class="table_row">
                                        <td class="yeartext_column">
                                            ประจำปี <span id="SpanYear2"> @item.Year </span> :
                                        </td>
                                        <td class="filenametext_column" id="TextFiles">
                                            @item.FileName
                                        </td>
                                        <td class="download_button_column">

                                            <a class="btn" href="~/Repository/PDF/ActionPlan/@item.FileName?@GenerateMath()"
                                               target="_blank" title="ไฟล์เอกสาร" id="LinkFiles">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-book-download" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="#444" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                                    <path d="M12 20h-6a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12v5"></path>
                                                    <path d="M13 16h-7a2 2 0 0 0 -2 2"></path>
                                                    <path d="M15 19l3 3l3 -3"></path>
                                                    <path d="M18 22v-9"></path>
                                                </svg>
                                            </a>
                                        </td>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    const quarter = ["ไตรมาส 1", "ไตรมาส 1-2", "ไตรมาส 1-3", "ไตรมาส 1-4"];
    function getquarter(month) {
        return quarter[month - 1];
    }

    $('select[name="Filter"]').change(function (e) {
        let Year = $('#Year').val();
        let TopicID = '@ViewData["TopicID"]';
        $.ajax({
            type: "POST",
            url: '@Url.Action("FilterYear", "ActionPlan")',
            data: { Year: Year, TopicID: TopicID},
            dataType: "json",
            beforeSend: function () {
                // setting a timeout
                @*$("#loadMe").modal({
                    backdrop: "static", //remove ability to close modal with click
                    keyboard: false, //remove option to close with keyboard
                    show: true //Display loader!
                });*@
            },
            success: function (data) {
                console.log(data)
                if (data["Status"] == "-99") {
                    location.reload();
                }
                else if (data["Status"] == "1") {
                     @*console.log(data);*@

                     @*$("#loadMe").modal("hide");*@
                     Swal.fire(
                        'สำเร็จ',
                        data["Message"],
                        'success'
                     ).then(function () {
                         @*$("#loadMe").modal("hide");*@
                         $('#SpanYear').text(data["Data"][0].Year);
                         $('#SpanYear2').text(data["Data"][0].Year);
                         $('#TextFiles').text(data["Data"][0].FileName);
                         $("#LinkFiles").attr("href", "../Repository/PDF/ActionPlan/" + data["Data"][0].FileName + "?@GenerateMath()");

                     });
                }
                else {
                     Swal.fire({
                        icon: 'error',
                        title: 'เกิดความผิดพลาด!',
                        text: data["Message"],
                     }).then(function () {
                         @*$("#loadMe").modal("hide");*@
                         $('#SpanYear').text(Year);
                         $('#SpanYear2').text(Year);
                         $('#TextFiles').text("");
                         $("#LinkFiles").attr("href", "javascript:toggleMe(0);");
                     });
                }
            },
            error: function (error) {
                @*alert(error);*@
                @*$("#loadMe").modal("hide");*@

                Swal.fire({
                    icon: 'error',
                    title: 'เกิดความผิดพลาด!',
                    text: error["Message"],
                })
            }
        });
    });
</script>

iPMS/Views/ActionPlan/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>